// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMjVlAvT5jBb4hXJpcdq_c8XG5AZFIeD0',
    appId: '1:338204188518:web:777ed5640b0f93759ef2a7',
    messagingSenderId: '338204188518',
    projectId: 'subway-enforcement-app',
    authDomain: 'subway-enforcement-app.firebaseapp.com',
    storageBucket: 'subway-enforcement-app.firebasestorage.app',
    measurementId: 'G-DBQ5Z43HY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtxQKaQiE9TacEMyeBDSzqrJb_JbkJCWs',
    appId: '1:338204188518:android:38f208fab6e7e20a9ef2a7',
    messagingSenderId: '338204188518',
    projectId: 'subway-enforcement-app',
    storageBucket: 'subway-enforcement-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMjVlAvT5jBb4hXJpcdq_c8XG5AZFIeD0',
    appId: '1:338204188518:web:bbe3750d4017c8099ef2a7',
    messagingSenderId: '338204188518',
    projectId: 'subway-enforcement-app',
    authDomain: 'subway-enforcement-app.firebaseapp.com',
    storageBucket: 'subway-enforcement-app.firebasestorage.app',
    measurementId: 'G-HX05G7KRQW',
  );
}
